############################################################
#############  缓存配置 (多环境)
#############  Cache Configuration (Multi-Environment)
############################################################

spring:
  # Redisson 配置
  redisson:
    config: classpath:redis/redisson-single.yml

  ############################################################
  #############  EhCache 配置
  ############################################################
  cache:
    type: ehcache

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  ###########################################################
  ############ Redis 配置
  ###########################################################
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 3000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  cache:
    ehcache:
      config: classpath:config/cache/ehcache-dev.xml

---
# 测试环境配置
spring:
  config:
    activate:
      on-profile: test
  ###########################################################
  ############ Redis 配置
  ###########################################################
  redis:
    host: ${REDIS_HOST:test-redis-server}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:1}
    timeout: 5000ms
    jedis:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 2
  cache:
    ehcache:
      config: classpath:config/cache/ehcache-test.xml

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
  ###########################################################
  ############ Redis 配置
  ###########################################################
  redis:
    # 生产环境使用环境变量配置Redis
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
    database: ${REDIS_DATABASE:0}
    timeout: 10000ms
    ssl: ${REDIS_SSL:false}
    jedis:
      pool:
        max-active: 100
        max-wait: 10000ms
        max-idle: 20
        min-idle: 5
        time-between-eviction-runs: 60000ms
  redisson:
    config: classpath:redis/redisson-cluster.yml
  cache:
    ehcache:
      config: classpath:config/cache/ehcache-prod.xml