############################################################
#############  安全配置 (多环境)
#############  Security Configuration (Multi-Environment)
############################################################

##########################################################################
#############  安全认证配置
##########################################################################
topinfo:
  # 安全配置
  security:
    # 启用鉴权控制
    enable: true
    # 密码传输是否加密
    password-encryption: true
    # 认证配置
    authentication:
      # 配置不需要认证的路径
      excludePaths:
        - /static/**
        - /sys/captcha/**
        - /sys/file/preview-pdf

############################################################
#############  文件服务器配置
############################################################
  jdfs:
    client:
      # 模式： 本地模式（local）-默认，服务器模式（server）
      model: local

############################################################
#############  Keycloak 配置
############################################################
keycloak:
  sso:
    # 启用 Keycloak SSO
    enabled: true
    # JWT 验证配置
    jwt:
      verify-expiration: true
      verify-issuer: true
      verify-audience: false
    # 用户信息头配置
    user-header:
      user-id-header: X-User-Id
      username-header: X-Username
      email-header: X-User-Email
      name-header: X-User-Name
      roles-header: X-User-Roles
      permissions-header: X-User-Permissions
  # 管理员配置
  admin:
    client-id: admin-cli

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  mail:
    # SMTP服务器地址
    host: smtp.163.com
    # SMTP服务器端口（163邮箱SSL端口）
    port: 465
    # 发送邮件的邮箱账号
    username: 18069853753@163.com
    # 邮箱密码或授权码
    password: WQbFDS7fdK92fKcU
    # 邮件编码
    default-encoding: UTF-8
    # SMTP配置
    properties:
      mail:
        smtp:
          # 启用SMTP认证
          auth: true
          # 启用SSL加密
          ssl:
            enable: true
          # SSL端口
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
topinfo:
  security:
    authentication:
      excludePaths:
        - /static/**
        - /sys/captcha/**
        - /sys/file/preview-pdf
        - /sys/person/account-findpwd
        - /sys/person/check-vcode
        - /sys/**
        - /sys/person/getUserInfo
        # 图形验证
        - /**
        - /api/**
        - /app/sys/captcha/verification-image
        - /platform/captcha/get-slider-captcha
        # 附件下载
        - /sys/file/download
        - /app/sys/file/download
        - /app/**
        - /api/**
        - /platform/**
        - /app/sys/file/upload
        - /app/trainoffline/**
        - /gdemergencyvehicle/sgddcreservation/**
        - /common/clientlogin/getPhoneByLoginName
        - /common/clientlogin/sendMsg
        - /common/clientlogin/checkPhoneCode
        - /taskcheck/siccheckpoint/**
        - /taskcheck/sicchecktask/**
        # 开发环境额外路径
        - /druid/**
        - /actuator/**
  jdfs:
    client:
      # 模式： 本地模式（local）-默认，服务器模式（server）
      model: local
      local:
        logical-disk:
          # 逻辑盘名称
          D1:
            # 开发环境存储目录
            dir: D:\upload\jdfs
            # 盘的读写 rw
            status: rw
keycloak:
  # Keycloak 服务器地址
  server-url: http://localhost:18080
  # Realm 名称
  realm: ps-realm
  sso:
    # Keycloak 服务器地址
    server-url: http://localhost:18080
    # Realm 名称
    realm: ps-realm
    # 客户端 ID
    client-id: ps-be
    # 客户端密钥（开发环境可以明文，生产环境使用环境变量）
    client-secret: xMXvDGzby4Z48szob7i2fuZlZy5Wlqrh
    # 回调重定向配置
    redirect:
      # 登录成功后重定向地址
      success-url: http://localhost:10801/#/sso/login
      # 登录失败后重定向地址
      error-url: http://localhost:10801/#/login 
    # JWT 验证配置
    jwt:
      # Token 缓存时间（秒）
      cache-ttl: 300
  # 管理员配置
  admin:
    # 管理员用户名
    username: admin
    # 管理员密码
    password: admin123

---
# 测试环境配置
spring:
  config:
    activate:
      on-profile: test
  mail:
    # 测试环境邮件配置
    host: ${MAIL_HOST:test-mail-server}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
topinfo:
  security:
    authentication:
      excludePaths:
        - /static/**
        - /sys/captcha/**
        - /sys/file/preview-pdf
        - /sys/person/account-findpwd
        - /sys/person/check-vcode
        - /api/**
        - /app/sys/captcha/verification-image
        - /platform/captcha/get-slider-captcha
        - /sys/file/download
        - /app/sys/file/download
        - /app/**
        - /platform/**
        - /app/sys/file/upload
        # 测试环境健康检查
        - /actuator/health
  jdfs:
    client:
      # 测试环境使用服务器模式
      model: server
      server:
        # 文件服务器地址
        server-host: ${FILE_SERVER_HOST:test-file-server}
        # netty服务器监听的端口
        netty-port: 8877
        # work 线程组
        work-group: 12
        # 数据帧最大长度
        max-frame-length: 1048576
        # tomcat服务器监听的端口
        tomcat-port: 8080
        # 文件服务器应用名称
        application-name: topinfo-platform-jdfs-storage
keycloak:
  # Keycloak 服务器地址
  server-url: ${KEYCLOAK_SERVER_URL:http://test-keycloak:8080}
  # Realm 名称
  realm: ps-realm-test
  sso:
    # Keycloak 服务器地址
    server-url: ${KEYCLOAK_SERVER_URL:http://test-keycloak:8080}
    # Realm 名称
    realm: ps-realm-test
    # 客户端 ID
    client-id: ps-be-test
    # 客户端密钥（使用环境变量）
    client-secret: ${KEYCLOAK_CLIENT_SECRET}
    # 回调重定向配置
    redirect:
      # 登录成功后重定向地址
      success-url: ${FRONTEND_URL:http://test-frontend}/#/sso/login
      # 登录失败后重定向地址
      error-url: ${FRONTEND_URL:http://test-frontend}/#/login
    # JWT 验证配置
    jwt:
      cache-ttl: 600
  # 管理员配置
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD}

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
  mail:
    # 生产环境邮件配置（使用环境变量）
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            # 如果使用SSL
            enable: ${MAIL_SSL_ENABLED:false}
          socketFactory:
            port: ${MAIL_SSL_PORT:465}
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
topinfo:
  security:
    authentication:
      # 生产环境严格控制不需要认证的路径
      excludePaths:
        - /static/**
        - /sys/captcha/**
        - /sys/file/preview-pdf
        - /api/health
        - /actuator/health
  jdfs:
    client:
      # 生产环境使用服务器模式
      model: server
      server:
        # 文件服务器地址（使用环境变量）
        server-host: ${FILE_SERVER_HOST}
        # netty服务器监听的端口
        netty-port: ${FILE_SERVER_NETTY_PORT:8877}
        # work 线程组
        work-group: ${FILE_SERVER_WORK_GROUP:24}
        # 数据帧最大长度
        max-frame-length: 1048576
        # tomcat服务器监听的端口
        tomcat-port: ${FILE_SERVER_TOMCAT_PORT:8080}
        # 文件服务器应用名称
        application-name: topinfo-platform-jdfs-storage
keycloak:
  # Keycloak 服务器地址（使用环境变量）
  server-url: ${KEYCLOAK_SERVER_URL}
  # Realm 名称
  realm: ${KEYCLOAK_REALM:ps-realm}
  sso:
    # 启用 Keycloak SSO
    enabled: ${KEYCLOAK_SSO_ENABLED:true}
    # Keycloak 服务器地址
    server-url: ${KEYCLOAK_SERVER_URL}
    # Realm 名称
    realm: ${KEYCLOAK_REALM:ps-realm}
    # 客户端 ID
    client-id: ${KEYCLOAK_CLIENT_ID:ps-be}
    # 客户端密钥（必须使用环境变量）
    client-secret: ${KEYCLOAK_CLIENT_SECRET}
    # 回调重定向配置
    redirect:
      # 登录成功后重定向地址
      success-url: ${FRONTEND_URL}/#/sso/login
      # 登录失败后重定向地址
      error-url: ${FRONTEND_URL}/#/login
    # JWT 验证配置
    jwt:
      verify-audience: true
      cache-ttl: ${KEYCLOAK_JWT_CACHE_TTL:1800}
  # 管理员配置
  admin:
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}