############################################################
#############  测试环境安全配置
#############  Test Security Configuration
############################################################

##########################################################################
#############  安全认证配置
##########################################################################
topinfo:
  # 安全配置
  security:
    # 启用鉴权控制
    enable: true
    # 密码传输是否加密
    password-encryption: true
    # 认证配置
    authentication:
      # 配置不需要认证的路径
      excludePaths:
        - /static/**
        - /sys/captcha/**
        - /sys/file/preview-pdf
        - /sys/person/account-findpwd
        - /sys/person/check-vcode
        - /api/**
        - /app/sys/captcha/verification-image
        - /platform/captcha/get-slider-captcha
        - /sys/file/download
        - /app/sys/file/download
        - /app/**
        - /platform/**
        - /app/sys/file/upload
        # 测试环境健康检查
        - /actuator/health

############################################################
#############  文件服务器配置
############################################################
  jdfs:
    client:
      # 测试环境使用服务器模式
      model: server
      server:
        # 文件服务器地址
        server-host: ${FILE_SERVER_HOST:test-file-server}
        # netty服务器监听的端口
        netty-port: 8877
        # work 线程组
        work-group: 12
        # 数据帧最大长度
        max-frame-length: 1048576
        # tomcat服务器监听的端口
        tomcat-port: 8080
        # 文件服务器应用名称
        application-name: topinfo-platform-jdfs-storage

############################################################
#############  Keycloak 配置（测试环境）
############################################################
keycloak:
  # Keycloak 服务器地址
  server-url: ${KEYCLOAK_SERVER_URL:http://test-keycloak:8080}
  # Realm 名称
  realm: ps-realm-test
  sso:
    # 启用 Keycloak SSO
    enabled: true
    # Keycloak 服务器地址
    server-url: ${KEYCLOAK_SERVER_URL:http://test-keycloak:8080}
    # Realm 名称
    realm: ps-realm-test
    # 客户端 ID
    client-id: ps-be-test
    # 客户端密钥（使用环境变量）
    client-secret: ${KEYCLOAK_CLIENT_SECRET}
    # 回调重定向配置
    redirect:
      # 登录成功后重定向地址
      success-url: ${FRONTEND_URL:http://test-frontend}/#/sso/login
      # 登录失败后重定向地址
      error-url: ${FRONTEND_URL:http://test-frontend}/#/login
    # JWT 验证配置
    jwt:
      verify-expiration: true
      verify-issuer: true
      verify-audience: false
      cache-ttl: 600
    # 用户信息头配置
    user-header:
      user-id-header: X-User-Id
      username-header: X-Username
      email-header: X-User-Email
      name-header: X-User-Name
      roles-header: X-User-Roles
      permissions-header: X-User-Permissions
  # 管理员配置
  admin:
    client-id: admin-cli
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD}

############################################################
#############  邮件服务配置（测试环境）
############################################################
spring:
  mail:
    # 测试环境邮件配置
    host: ${MAIL_HOST:test-mail-server}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true