version: '3.8'

services:
  # Nginx反向代理服务
  nginx-proxy:
    image: nginx:1.25-alpine
    container_name: ps-nginx-proxy
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./ps-be/nginx:/etc/nginx/conf.d:ro
      - nginx_logs:/var/log/nginx
    networks:
      - keycloak-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - keycloak
      - redis

  # PostgreSQL数据库 - Keycloak使用
  postgres:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - keycloak-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Keycloak身份认证服务器
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    container_name: keycloak-server
    environment:
      # 数据库配置
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      
      # Keycloak管理员账户
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      
      # 开发模式配置
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    command:
      - start-dev
    ports:
      - "18080:8080"
    networks:
      - keycloak-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # MySQL数据库 - 应用使用
  mysql:
    image: mysql:5.7
    container_name: ps-mysql
    environment:
      MYSQL_ROOT_PASSWORD: W4HV=QxtHz
      MYSQL_DATABASE: ps-bmp
      MYSQL_USER: ps-user
      MYSQL_PASSWORD: ps-password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - keycloak-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Redis缓存服务
  redis:
    image: redis:7-alpine
    container_name: ps-redis
    ports:
      - "6379:6379"
    networks:
      - keycloak-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local
  redis_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  keycloak-network:
    driver: bridge