############################################################
#############  开发环境配置
#############---------------------------------##############
#############  port: Tomcat服务端口
############################################################
server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    # 设定HttpHeader请求头大小
    # 设定Httppost数据大小
    max-http-form-post-size: 10MB
  servlet:
    context-path: /ps-be
  max-http-header-size: 10MB

# Spring Boot标准数据源配置
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://alilaoba.cn:13307/ps-bmp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: W4HV=QxtHz
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 500
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  ###########################################################
  ############ topinfo-platform-redisson-starter 配置
  ###########################################################
  #----------------------------------------------------------
  #引用 redis/redisson-single.yml配置
  #注释配置不引用redis，类似开关
  #----------------------------------------------------------
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 3000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  redisson:
    config: classpath:redis/redisson-single.yml
  # 邮件服务配置
  mail:
    # SMTP服务器地址
    host: smtp.163.com
    # SMTP服务器端口（163邮箱SSL端口）
    port: 465
    # 发送邮件的邮箱账号
    username: 18069853753@163.com
    # 邮箱密码或授权码
    password: WQbFDS7fdK92fKcU
    # 邮件编码
    default-encoding: UTF-8
    # SMTP配置
    properties:
      mail:
        smtp:
          # 启用SMTP认证
          auth: true
          # 启用SSL加密
          ssl:
            enable: true
          # SSL端口
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

##########################################################################
#############  topinfo-platform-mybatis-starter-autoconfigurer
#############  配置模板
##########################################################################
topinfo:
  mybatis:
    ## 数据中心（可选）
    datacenterId: 0
    ## 机器（可选）
    machineId: 0
    ## 数据源配置
    datasource-config:
      # mysql数据库接配置
      url: jdbc:mariadb://alilaoba.cn:13307/ps-bmp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      # 用户名
      username: root
      # 密码
      password: W4HV=QxtHz
      ## 最新连接数（可选）， 默认：5
      minIdle: 5
      ## 最大连接数（可选）， 默认：500
      maxActive: 500
      ## 校验连接sql（可选）, 默认： SELECT 1
      validationQuery: SELECT 1
    ## 租户模式（可选）
    tenant: false
    ## 忽略不需要添加租户条件的表, 数组（可选）
    ignore-tenant-tables:
      - test


  ##########################################################################
  #############  topinfo-platform-security-starter-autoconfigurer
  #############  配置模板
  ##########################################################################
  # 安全 ------------------------------------------------------------------------
  security:
    # 启用鉴权控制
    enable: true
    # 密码传输是否加密，默认不加密
    password-encryption: true
    # 认证配置
    authentication:
      # 配置不需要认证的路径
      excludePaths:
        - /static/**
        - /sys/captcha/**
        - /sys/file/preview-pdf
        - /sys/person/account-findpwd
        - /sys/person/check-vcode
        - /sys/**
        - /sys/person/getUserInfo
        # 图形验证
        - /**
        - /api/**
        - /app/sys/captcha/verification-image
        - /platform/captcha/get-slider-captcha
        # 附件下载
        - /sys/file/download
        - /app/sys/file/download
        - /app/**
        - /api/**
        - /platform/**
        - /app/sys/file/upload
        - /app/trainoffline/**
        - /gdemergencyvehicle/sgddcreservation/**
        - /common/clientlogin/getPhoneByLoginName
        - /common/clientlogin/sendMsg
        - /common/clientlogin/checkPhoneCode
        - /enterparkmanage/**
        - /taskcheck/siccheckpoint/**
        - /taskcheck/sicchecktask/**
  ############################################################
  #############  文件服务器配置
  ############################################################
  jdfs:
    client:
      # 模式： 本地模式（local）-默认，服务器模式（server）
      model: local
      local:
        ############################################################
        ############# logical-disk : 逻辑盘
        ############# 存储目录最少配置一个
        ############################################################
        logical-disk:
          # 逻辑盘名称
          D1:
            # 存储目录
            dir: D:\upload\jdfs
            # 盘的读写 rw
            status: rw
      server:
        # 服务器地址
        server-host: 192.168.0.43
        # netty服务器监听的端口, 默认: 8888
        netty-port: 8877
        # work 线程组用于数据处理, 默认是系统CPU个数的两倍，也可以根据实际情况指定
        work-group: 24
        # 数据帧最大长度，合理设置可避免大数据包攻击你的服务器, 我们可以设置为1M = 1024*1024
        max-frame-length: 1048576
        # tomcat服务器监听的端口, 默认: 8080
        tomcat-port: 8080
        # 文件服务器应用名称
        application-name: topinfo-platform-jdfs-storage


#危化车辆管理(移动端查看准入、放行二维码）
url-vehiclereservation: http://172.16.100.111:8081

######海康视频相关配置#####
iscvideo:
  host: 36.212.163.101:4443
  appKey: 22894988
  appSecret: VDPYssrD2b4Dm0HmPHvj
  artemisPath: /artemis
  # 获取单个视频地址接口
  cameraRealPath: /api/video/v2/cameras/previewURLs
  # 请求类型 https或http
  requestType: https://
  # 视频取流协议，默认使用httpflv，低版本可改成hls
  protocol: ws
  expand: transcode=1&videotype=h264&streamform=ps


#采集服务接口调用配置
collectsys:
  #IOT平台地址
  #  url: http://116.178.218.171:86/iot-center/
  url: http://36.212.164.63:86/iot-center/
  #获取IOT平台token参数
  #  appKey: 1685968337873539072
  appKey: 1808687605643087872
  #  appKey:
  #  appSecret: IUM451XLIBMMRS9p9AXoWOuldPrVD8z4
  appSecret: le1i9rV75I8kNSM9zraB4fUg4bVB2huW

shotmsg:
  config:
    # 东方临港短信平台配置
    dflgurl: http://msg.hibnet.com:9993/services/SmsService
    clientID: 162
    Sharedsecret: p6{Nc9]JyF&2



############################################################
############# logging 日志配置 - 开发环境
############################################################  
logging:
  level:
    # MyBatis SQL日志 - 显示完整SQL和参数
    com.jiuxi.admin: DEBUG
    # MyBatis框架日志 - 显示SQL执行过程
    org.mybatis: DEBUG
    # MyBatis-Plus日志 - 显示增强功能日志
    com.baomidou.mybatisplus: DEBUG
    # 数据库连接池日志 - 显示连接管理
    com.alibaba.druid: DEBUG
    # SQL执行日志 - 显示详细执行信息
    org.apache.ibatis: DEBUG
    # 显示SQL参数绑定和结果集
    org.springframework.jdbc: DEBUG
    # 显示SQL执行时间和性能信息
    org.springframework.jdbc.core: DEBUG
    # 显示事务管理日志
    org.springframework.transaction: DEBUG
    # 显示数据源相关日志
    org.springframework.jdbc.datasource: DEBUG

# 入园申请管理
enterParkManage:
  # 微信小程序ID
  appId: wx4d38ffbe2e08e6b7
  # 微信小程序密钥
  appSecret: 21e0c82bf4feb3fd2c7cef69c75cec23
  # 奎屯（测试）
  chemparkId: 100348676441899022
  # 乳源园区ID
  # chemparkId: 100467702434368253

localtion:
  host: http://192.168.90.227:8091/location-service
  hisDataUrl: /api/td/getDataHis
  nowDataUrl: /api/td/getData

# Keycloak SSO 配置
keycloak:
  sso:
    # 启用 Keycloak SSO
    enabled: true
    # Keycloak 服务器地址
    server-url: http://localhost:8180
    # Realm 名称
    realm: ps-realm
    # 客户端 ID
    client-id: ps-be
    # 客户端密钥（如果需要）
    client-secret: xMXvDGzby4Z48szob7i2fuZlZy5Wlqrh
    # 回调重定向配置
    redirect:
      # 登录成功后重定向地址
      success-url: http://localhost:10801/#/sso/login
      # 登录失败后重定向地址
      error-url: http://localhost:10801/#/login 
    # JWT 验证配置
    jwt:
      # 是否验证 Token 过期时间
      verify-expiration: true
      # 是否验证签发者
      verify-issuer: true
      # 是否验证受众
      verify-audience: false
      # Token 缓存时间（秒）
      cache-ttl: 300
    # 用户信息头配置（从 Nginx 代理获取）
    user-header:
      # 用户 ID 头名称
      user-id-header: X-User-Id
      # 用户名头名称
      username-header: X-Username
      # 邮箱头名称
      email-header: X-User-Email
      # 姓名头名称
      name-header: X-User-Name
      # 角色头名称
      roles-header: X-User-Roles
      # 权限头名称
      permissions-header: X-User-Permissions